-- Schema as Hibernate generated it before migrations were introduced.
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(255) CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE galym (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    description varchar(255) NOT NULL,
    type varchar(255) CONSTRAINT galym_type_check CHECK (
        type IN ('INTERNSHIP', 'MASTERS', 'SCHOLARSHIP', 'EXCHANGE_PROGRAM', 'RESEARCH', 'OTHER')
    ),
    country varchar(255) NOT NULL,
    city varchar(255) NOT NULL,
    organization_name varchar(255) NOT NULL,
    eligibility varchar(255) NOT NULL,
    application_instructions varchar(255) NOT NULL,
    application_deadline date,
    funding_info varchar(255) NOT NULL,
    has_scholarship boolean NOT NULL,
    application_link varchar(255),
    status varchar(255) CONSTRAINT galym_status_check CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_by_user_id bigint,
    created_at timestamp(6),
    updated_at timestamp(6)
);
